apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1200
      database: ${POSTGRES_DB}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
